### ISSUE TITLE
Wiremock `isAlive` fails when the backend responds with `HTTP/1.0`

### ISSUE THREAD

**Issue by cristiangrama** [rowanhill/wiremock-php#9]
For some reason when using `get_headers` the default protocol version used to make the request is `HTTP/1.0`. If the server accepts both then it will respond with `HTTP/1.0` and this will break the check in the `HttpWait` class https://github.com/rowanhill/wiremock-php/blob/master/src/WireMock/Client/HttpWait.php#L19.

This is the response I get while serving wiremock with Traefik.
```
array:5 [
  0 => "HTTP/1.0 200 OK"
  1 => "Content-Type: application/json"
  2 => "Server: Jetty(9.2.z-SNAPSHOT)"
  3 => "Date: Tue, 19 Jun 2018 17:30:16 GMT"
  4 => "Content-Length: 56"
]
```

Should we add a check for all supported HTTP versions? Any reason why the check is hardcoded for version 1.1?

**Comment by rowanhill** [comment]
Hi @cristiangrama 

First, sorry for the slow reply - I somehow missed this issue being raised!

I don't think there's a good reason for the check requiring HTTP/1.1 - I guess it works in most cases (because bare WireMock run in standalone mode will respond with HTTP/1.1), but I hadn't considered reverse proxies in front of WireMock.

Do you fancy submitting a PR?
